trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: aws-creds
  - name: awsRegion
    value: "us-east-1"
  - name: clusterName
    value: "my-eks-cluster"

stages:
  - stage: InstallMonitoring
    jobs:
      - job: InstallPrometheusGrafana
        steps:
          - checkout: self

          - script: |
              echo "Exporting AWS credentials..."
              export AWS_ACCESS_KEY_ID=$(AWS-ACCESS-KEY-ID)
              export AWS_SECRET_ACCESS_KEY=$(AWS-SECRET-ACCESS-KEY)
              export AWS_DEFAULT_REGION=$(AWS-DEFAULT-REGION)

              echo "✅ Verifying AWS identity..."
              aws sts get-caller-identity

              echo "🔄 Updating kubeconfig..."
              aws eks --region $(awsRegion) update-kubeconfig --name $(clusterName)

              echo "➕ Adding Prometheus community repo..."
              helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
              helm repo update

              echo "🚀 Installing Prometheus & Grafana..."
              helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
                --namespace monitoring --create-namespace \
                --set grafana.service.type=LoadBalancer \
                --set prometheus.service.type=LoadBalancer
            displayName: "Install Prometheus & Grafana with Helm"
            env:
              AWS_ACCESS_KEY_ID: $(AWS-ACCESS-KEY-ID)
              AWS_SECRET_ACCESS_KEY: $(AWS-SECRET-ACCESS-KEY)
              AWS_DEFAULT_REGION: $(AWS-DEFAULT-REGION)
