replicaCount: 2

image:
  repository: "638067550830.dkr.ecr.us-east-1.amazonaws.com/2048" # <-- this will be replaced dynamically in the pipeline
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources: {}
